name: Create Pull Request

on:
  push:
    branches:
      - test1
      - test2

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'Merge changes from ${GITHUB_REF}'
          body: 'This pull request merges changes from ${GITHUB_REF}'
          base: main
          head: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
