name: Create Pull Request on Push

on:
  push:
    branches:
      - '**'  # 모든 브랜치에서 push 이벤트를 수신하도록 설정

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: "Automated Pull Request"
        body: "This pull request was created automatically from the branch ${{ github.ref_name }}."
        base: main
        head: ${{ github.ref_name }} 
        draft: false  
